Repository InsightSSG/Net-Manage, pull requests merged in 2023-08, with the labels that each got.

#401 Create README.md #158
  .gitignore
  .streamlit/secrets_example.toml
  netmanage/collectors/meraki_collectors.py
  netmanage/collectors/netbox_collectors.py
  netmanage/run_collectors.py
  test/test_meraki_collectors.py
Labels: documentation

#409 Fix incorrect run_collectors import in test_meraki_collectors.py #408
  netmanage/run_collectors.py
  test/test_meraki_collectors.py
Labels: bug

#410 Resolving merge conflict
  netmanage/run_collectors.py
Labels: bug

#423 Split parsers from collectors
  netmanage/__init__.py
  netmanage/collectors/cisco_ios_collectors.py
  netmanage/parsers/__init__.py
  netmanage/parsers/cisco_ios_parsers.py
Labels: enhancement

#425 Resolve #422 and #424
  .env_example
  netmanage/collectors/cisco_ios_collectors.py
  netmanage/collectors/f5_collectors.py
  netmanage/helpers/f5_helpers.py
  netmanage/helpers/helpers.py
  netmanage/parsers/f5_parsers.py
  netmanage/run_collectors.py
  netmanage/setup.py
  playbooks/f5_run_adhoc_commands.yml
Labels: bug, enhancement

#434 Resolves #433, #435
  net-manage.ipynb
  netmanage/collectors/cisco_ios_collectors.py
  netmanage/helpers/helpers.py
  netmanage/helpers/obfuscate_addresses.py
  netmanage/parsers/cisco_ios_parsers.py
  netmanage/run_collectors.py
Labels: enhancement
