Repository InsightSSG/Net-Manage, pull requests merged in 2023-06, with the labels that each got.

#267 Create collector to get group names from Solarwinds NPM #266
  collectors/solarwinds_collectors.py
  helpers/helpers.py
  net-manage.ipynb
  requirements.txt
  run_collectors.py
  writers/cisco_nxos_writers.py
Labels: enhancement

#269 Create collector to get group members from Solarwinds NPM #268
  collectors/solarwinds_collectors.py
  helpers/helpers.py
  net-manage.ipynb
  run_collectors.py
Labels: enhancement

#272 Resolves #270 and #271
  collectors/solarwinds_collectors.py
  helpers/helpers.py
  run_collectors.py
Labels: enhancement

#274 Create function to get vendor for a Solarwinds NPM node #273
  collectors/solarwinds_collectors.py
Labels: enhancement

#285 Create collector to get all node serial numbers from Solarwinds NCM #284
  collectors/solarwinds_collectors.py
  helpers/helpers.py
  net-manage.ipynb
  run_collectors.py
Labels: enhancement

#286 Create collector to get all Solarwinds NPM node IDs #281
  collectors/solarwinds_collectors.py
  helpers/helpers.py
  run_collectors.py
Labels: enhancement

#289 Create collector to get all container (group) data from Solarwinds NPM #288
  collectors/solarwinds_collectors.py
  net_discovery_with_solarwinds.ipynb
Labels: enhancement

#290 Create collector to get all container data from Solarwinds NPM #288
  collectors/solarwinds_collectors.py
  helpers/helpers.py
  run_collectors.py
Labels: enhancement

#295 Create collector to get VRFs on Cisco IOS devices #294
  collectors/cisco_ios_collectors.py
  helpers/helpers.py
  run_collectors.py
Labels: enhancement

#300 Resolves #298 and #299
  collectors/cisco_ios_collectors.py
  helpers/helpers.py
  playbooks/cisco_ios_gather_facts.yml
  run_collectors.py
Labels: enhancement

#297 Move ios collectors to cisco ios collectors
  collectors/cisco_ios_collectors.py
  collectors/collectors.py
  net-manage.ipynb
  net_discovery_with_solarwinds.ipynb
  run_collectors.py
  test/test_cisco_ios_collectors.py
Labels: enhancement

#305 Resolves #238, #302, #303
  collectors/collectors.py
  collectors/palo_alto_collectors.py
  helpers/helpers.py
  net-manage.ipynb
  run_collectors.py
Labels: bug, enhancement

#310 Create interface_ip_addresses collector for Cisco ASA #309
  collectors/cisco_asa_collectors.py
  collectors/collectors.py
  net-manage.ipynb
  run_collectors.py
Labels: enhancement

#312 Add subnet details to F5 self_ips collector #311
  collectors/f5_collectors.py
  net-manage.ipynb
Labels: enhancement

#315 Meraki collectors are failing #313
  collectors/meraki_collectors.py
  helpers/helpers.py
  net-manage.ipynb
  run_collectors.py
Labels: bug

#318 Create Meraki collector to get VLANs in an appliance network #316
  collectors/meraki_collectors.py
  helpers/helpers.py
  run_collectors.py
Labels: enhancement

#282 Update f5_collectors.py
  collectors/f5_collectors.py
Labels: bug

#321 Add docstring and comments to network_appliance_vlans collector #320
  collectors/meraki_collectors.py
Labels: documentation

#327 Resolves #323, #324, #325, #326
  collectors/meraki_collectors.py
  collectors/netbox_collectors.py
  helpers/helpers.py
  requirements.txt
  test/test_palo_alto_collectors.py
Labels: enhancement

#319 Move nxos collectors
  collectors/cisco_nxos_collectors.py
  collectors/collectors.py
  run_collectors.py
  test/test_cisco_nxos_collectors.py
Labels: enhancement

#329 Create writers file for Netbox #328
  writers/__init__.py
  writers/netbox_writers.py
Labels: enhancement

#331 Create Netbox collector to get VRF details #330
  collectors/netbox_collectors.py
Labels: enhancement

#333 Optimize netbox_get_vrf_details collector and add error checking #332
  collectors/netbox_collectors.py
Labels: enhancement

#335 Create netbox writer to create a VRF #334
  writers/netbox_writers.py
Labels: enhancement

#337 add_netbox_prefix writer is failing when VRF name is provided #336
  writers/netbox_writers.py
Labels: bug

#343 Create collector to get devices from Cisco DNAC #342
  collectors/dnac_collectors.py
  helpers/helpers.py
  requirements.txt
Labels: enhancement

#345 Create DNAC collector to get module details for all devices #344
  collectors/dnac_collectors.py
  requirements.txt
Labels: enhancement
